membersrvc0:
  extends:
    file: compose-defaults.yml
    service: membersrvc

vp0:
  extends:
    file: docker-compose-security-base.yml
    service: vpSecurityBase
  environment:
    - CORE_PEER_ID=vp0
    - CORE_SECURITY_ENROLLID=test_vp0
    - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
  links:
    - membersrvc0
  ports:
    - 5000:5000

vp1:
  extends:
    file: docker-compose-security-base.yml
    service: vpSecurityBase
  environment:
    - CORE_PEER_ID=vp1
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:30303
    - CORE_SECURITY_ENROLLID=test_vp1
    - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy
  links:
    - membersrvc0
    - vp0
