vpSecurityBase:
  extends:
    file: compose-defaults.yml
    service: vp
  environment:
    - CORE_SECURITY_ENABLED=true
    - CORE_PEER_PKI_ECA_PADDR=membersrvc0:50051
    - CORE_PEER_PKI_TCA_PADDR=membersrvc0:50051
    - CORE_PEER_PKI_TLSCA_PADDR=membersrvc0:50051
